//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.1882
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace Main.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Main.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 居中 的本地化字符串。
        /// </summary>
        internal static string AlignCenter {
            get {
                return ResourceManager.GetString("AlignCenter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 左右对齐 的本地化字符串。
        /// </summary>
        internal static string AlignJustified {
            get {
                return ResourceManager.GetString("AlignJustified", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 靠左 的本地化字符串。
        /// </summary>
        internal static string AlignLeft {
            get {
                return ResourceManager.GetString("AlignLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 靠右 的本地化字符串。
        /// </summary>
        internal static string AlignRight {
            get {
                return ResourceManager.GetString("AlignRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许添加 的本地化字符串。
        /// </summary>
        internal static string AllowAdd {
            get {
                return ResourceManager.GetString("AllowAdd", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许删除 的本地化字符串。
        /// </summary>
        internal static string AllowDelete {
            get {
                return ResourceManager.GetString("AllowDelete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许导出EXCEL 的本地化字符串。
        /// </summary>
        internal static string AllowExcel {
            get {
                return ResourceManager.GetString("AllowExcel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许修改 的本地化字符串。
        /// </summary>
        internal static string AllowModify {
            get {
                return ResourceManager.GetString("AllowModify", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许打印 的本地化字符串。
        /// </summary>
        internal static string AllowPrint {
            get {
                return ResourceManager.GetString("AllowPrint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许保存 的本地化字符串。
        /// </summary>
        internal static string AllowSave {
            get {
                return ResourceManager.GetString("AllowSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许保存返回 的本地化字符串。
        /// </summary>
        internal static string AllowSaveReturn {
            get {
                return ResourceManager.GetString("AllowSaveReturn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许查询 的本地化字符串。
        /// </summary>
        internal static string AllowSearch {
            get {
                return ResourceManager.GetString("AllowSearch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 允许上传 的本地化字符串。
        /// </summary>
        internal static string AllowUpload {
            get {
                return ResourceManager.GetString("AllowUpload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是否要把此功能置于顶层？ 的本地化字符串。
        /// </summary>
        internal static string CanTop {
            get {
                return ResourceManager.GetString("CanTop", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Columns {
            get {
                object obj = ResourceManager.GetObject("Columns", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 一列 的本地化字符串。
        /// </summary>
        internal static string ColumnsOne {
            get {
                return ResourceManager.GetString("ColumnsOne", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二列 的本地化字符串。
        /// </summary>
        internal static string ColumnsTwo {
            get {
                return ResourceManager.GetString("ColumnsTwo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除此记录？ 的本地化字符串。
        /// </summary>
        internal static string DeleteBeforeConfirm {
            get {
                return ResourceManager.GetString("DeleteBeforeConfirm", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Depart {
            get {
                object obj = ResourceManager.GetObject("Depart", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 相同的代码，请修改！ 的本地化字符串。
        /// </summary>
        internal static string DuplicateCode {
            get {
                return ResourceManager.GetString("DuplicateCode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 错误! 的本地化字符串。
        /// </summary>
        internal static string Error {
            get {
                return ResourceManager.GetString("Error", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Exit {
            get {
                object obj = ResourceManager.GetObject("Exit", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 确定要退出本系统？ 的本地化字符串。
        /// </summary>
        internal static string ExitBeforeConfirm {
            get {
                return ResourceManager.GetString("ExitBeforeConfirm", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Flow {
            get {
                object obj = ResourceManager.GetObject("Flow", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 男 的本地化字符串。
        /// </summary>
        internal static string Man {
            get {
                return ResourceManager.GetString("Man", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Member {
            get {
                object obj = ResourceManager.GetObject("Member", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap MemberRole {
            get {
                object obj = ResourceManager.GetObject("MemberRole", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 否 的本地化字符串。
        /// </summary>
        internal static string No {
            get {
                return ResourceManager.GetString("No", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不允许为空！ 的本地化字符串。
        /// </summary>
        internal static string NoEmpty {
            get {
                return ResourceManager.GetString("NoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注意！ 的本地化字符串。
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 必须是数值！ 的本地化字符串。
        /// </summary>
        internal static string NumericalNote {
            get {
                return ResourceManager.GetString("NumericalNote", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是数值类型! 的本地化字符串。
        /// </summary>
        internal static string NumericalValeError {
            get {
                return ResourceManager.GetString("NumericalValeError", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Purview {
            get {
                object obj = ResourceManager.GetObject("Purview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 有关联项，不允许删除！ 的本地化字符串。
        /// </summary>
        internal static string RelatdItemsNoDelete {
            get {
                return ResourceManager.GetString("RelatdItemsNoDelete", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap Role {
            get {
                object obj = ResourceManager.GetObject("Role", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RoleMember {
            get {
                object obj = ResourceManager.GetObject("RoleMember", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap RolePurview {
            get {
                object obj = ResourceManager.GetObject("RolePurview", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择要删除的项！ 的本地化字符串。
        /// </summary>
        internal static string SelectDeleteItem {
            get {
                return ResourceManager.GetString("SelectDeleteItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先选择一个部门! 的本地化字符串。
        /// </summary>
        internal static string SelectDepart {
            get {
                return ResourceManager.GetString("SelectDepart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请选择某一项 的本地化字符串。
        /// </summary>
        internal static string SelectItem {
            get {
                return ResourceManager.GetString("SelectItem", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请先设置此功能对应的网页名 的本地化字符串。
        /// </summary>
        internal static string SetWebFile {
            get {
                return ResourceManager.GetString("SetWebFile", resourceCulture);
            }
        }
        
        internal static System.Drawing.Bitmap StatusTime {
            get {
                object obj = ResourceManager.GetObject("StatusTime", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap StausMember {
            get {
                object obj = ResourceManager.GetObject("StausMember", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap Table {
            get {
                object obj = ResourceManager.GetObject("Table", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap teban {
            get {
                object obj = ResourceManager.GetObject("teban", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TreeMenu {
            get {
                object obj = ResourceManager.GetObject("TreeMenu", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap TreeMenuVisible {
            get {
                object obj = ResourceManager.GetObject("TreeMenuVisible", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        internal static System.Drawing.Bitmap USER {
            get {
                object obj = ResourceManager.GetObject("USER", resourceCulture);
                return ((System.Drawing.Bitmap)(obj));
            }
        }
        
        /// <summary>
        ///   查找类似 女 的本地化字符串。
        /// </summary>
        internal static string Woman {
            get {
                return ResourceManager.GetString("Woman", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 是 的本地化字符串。
        /// </summary>
        internal static string Yes {
            get {
                return ResourceManager.GetString("Yes", resourceCulture);
            }
        }
    }
}
