//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行库版本:2.0.50727.832
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace WorkFlows.Properties {
    using System;
    
    
    /// <summary>
    ///   强类型资源类，用于查找本地化字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "2.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WorkFlows.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   为使用此强类型资源类的所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 确定要删除此记录？ 的本地化字符串。
        /// </summary>
        internal static string DeleteBeforeConfirm {
            get {
                return ResourceManager.GetString("DeleteBeforeConfirm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 结束环节 的本地化字符串。
        /// </summary>
        internal static string EndNode {
            get {
                return ResourceManager.GetString("EndNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 中间环节 的本地化字符串。
        /// </summary>
        internal static string MiddleNode {
            get {
                return ResourceManager.GetString("MiddleNode", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 分支 的本地化字符串。
        /// </summary>
        internal static string NodeTypeBranch {
            get {
                return ResourceManager.GetString("NodeTypeBranch", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 汇集 的本地化字符串。
        /// </summary>
        internal static string NodeTypeCollect {
            get {
                return ResourceManager.GetString("NodeTypeCollect", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 正常 的本地化字符串。
        /// </summary>
        internal static string NodeTypeNormal {
            get {
                return ResourceManager.GetString("NodeTypeNormal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不允许为空！ 的本地化字符串。
        /// </summary>
        internal static string NoEmpty {
            get {
                return ResourceManager.GetString("NoEmpty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注意！ 的本地化字符串。
        /// </summary>
        internal static string Note {
            get {
                return ResourceManager.GetString("Note", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 不是数值类型！ 的本地化字符串。
        /// </summary>
        internal static string NumericalValeError {
            get {
                return ResourceManager.GetString("NumericalValeError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 备注 的本地化字符串。
        /// </summary>
        internal static string Remarks {
            get {
                return ResourceManager.GetString("Remarks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起始环节 的本地化字符串。
        /// </summary>
        internal static string StartNode {
            get {
                return ResourceManager.GetString("StartNode", resourceCulture);
            }
        }
    }
}
